// maths object generated by a shape.
// can't be changed after it is created.

public class Bounds {
	private double x;
	private double y;
	private double width;
	private double height;
	
	public Bounds(double centerX, double centerY, double widthOfShape, double heightOfShape) {
		x = centerX;
		y = centerY;
		width = widthOfShape;
		height = heightOfShape;
	}
	
	// eml
	
	public double getCenterX() {
		return x;
	}
	
	public double getCenterY() {
		return y;
	}
	
	public double getWidth() {
		return width;
	}
	
	public double getHeight() {
		return height;
	}
	
	public double getTopLeftX() {
		return x - (width / 2);
	}
	
	public double getTopLeftY() {
		return y - (height / 2);
	}
	
	public double getBotRightX() {
		return x + (width / 2);
	}
	
	public double getBotRightY() {
		return y + (height / 2);
	}
	
	public boolean collidesWith(Bounds otherBounds) {
		
	}
}